# Generated by Django 5.0.3 on 2024-04-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
