# Generated by Django 5.0.3 on 2024-04-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='mysite/images/Noname.png', upload_to='images'),
        ),
    ]
