# Generated by Django 5.0.3 on 2024-04-20 16:07

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default=blog.models.default_photo, upload_to='images'),
        ),
    ]
